# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TV Maze Viewer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TV Maze Viewer
  pod 'Alamofire'
  pod 'Kingfisher'
end
